name: Build and Deploy # name 字段是 workflow 的名称
on: # on 字段指定触发 workflow 的条件，通常是某些事件，这里监听 master 分支上的 push 事件
  push:
    branches:
      - master
jobs: # workflow 文件的主体是 jobs 字段，表示要执行的一项或多项任务
  build-and-deploy: # job_id
    runs-on: ubuntu-latest # runs-on 字段指定运行所需要的虚拟机环境。它是必填字段，构建环境使用 ubuntu
    steps: # steps 字段指定每个 Job 的运行步骤，可以包含一个或多个步骤
      - name: Checkout # 步骤名称
        uses: actions/checkout@v2.3.1  
        with:
          persist-credentials: false

      - name: Install and Build # 下载依赖 打包项目
        run: |
          npm install
          npm run xlint
          npm run build

      - name: Deploy # 将打包内容发布到 github page
        uses: JamesIves/github-pages-deploy-action@3.7.1 # 使用别人写好的 actions
        with:  # 自定义环境变量
          ACCESS_TOKEN: ${{ secrets.LUCAS }}
          BRANCH: master
          FOLDER: dist
          REPOSITORY_NAME: houce/houce.github.io # 这是我的 github page 地址
          TARGET_FOLDER: github-actions-demo # 打包的文件将放到静态服务器 github-actions-demo 目录下

